platform :ios, '6.0'

pod 'AFNetworking', '2.0.3'
pod 'NPReachability', '0.1.0'
pod 'SDWebImage', '3.5.1'
pod 'UIActivityIndicator-for-SDWebImage', '1.0.3'
pod 'Parse', '1.2.16'
pod 'RESideMenu', '~> 3.3.1'
pod 'MBProgressHUD', '0.8'
pod 'InAppSettingsKit', '2.0'
